export const issues = [
  {
    id: 101,
    issueId: 1,
    title: "Fix bug in login",
    status: "Open",
    donations: 100,
    repo: "naizo01/OSS-Rewards-Agent",
  },
  {
    id: 102,
    issueId: 2,
    title: "Implement new feature",
    status: "In Progress",
    donations: 250,
    repo: "org/repo-a",
  },
  {
    id: 201,
    issueId: 1,
    title: "Improve performance",
    status: "Open",
    donations: 50,
    repo: "org/repo-b",
  },
  {
    id: 202,
    issueId: 2,
    title: "Update documentation",
    status: "Open",
    donations: 30,
    repo: "org/repo-b",
  },
  {
    id: 301,
    issueId: 1,
    title: "Refactor authentication system",
    status: "Open",
    donations: 150,
    repo: "org/repo-c",
  },
  {
    id: 401,
    issueId: 1,
    title: "Add dark mode support",
    status: "Open",
    donations: 0,
    repo: "org/repo-d",
  },
  {
    id: 402,
    issueId: 2,
    title: "Implement CI/CD pipeline",
    status: "Open",
    donations: 0,
    repo: "org/repo-d",
  },
];