[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
github_issue_reward = "9T4k3RZXv17Dy7bhExP45hHeQNEsjGokZZpe3hKrXS5f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[build]
sbf = true

[test]
startup_wait = 10000

[test.validator]
url = "http://127.0.0.1:8899"
