[profile.default]
src = "src"
out = "out"
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"},{ access = "read-write", path = "./"}]

libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
